spring:
  application:
    name: post-service
  cloud:
    config:
      import:
        - uri: http://localhost:9296
  thymeleaf:
    cache: false
  datasource:
    url: jdbc:mysql://localhost:3308/post_article_db?useSSL=false
    username: root
    password: mk123654
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update
      properties:
        hibernate:
          validator:
            apply_to_ddl: false
        dialect: org.hibernate.dialect.MySQL5Dialect
spring.kafka:
  bootstrap-servers: 127.0.0.1:39092, 127.0.0.1:29092
  producer:
    key-serializer: org.apache.kafka.common.serialization.LongSerializer
    value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  streams:
    properties:
      default.key.serde: org.apache.kafka.common.serialization.Serdes$LongSerde
      default.value.serde: org.springframework.kafka.support.serializer.JsonSerde
      spring.json.trusted.packages: "*"
    state-dir: /tmp/kafka-streams/


spring.output.ansi.enabled: ALWAYS

logging.pattern.console: "%clr(%d{HH:mm:ss.SSS}){blue} %clr(---){faint} %clr([%15.15t]){yellow} %clr(:){red} %clr(%m){faint}%n"

server:
  port: 8080