server:
  port: 8089

spring:
  datasource:
    url: jdbc:mysql://localhost:3310/chatdb?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
  application:
    name: CHATS-SERVICE
  config:
    import: optional:configserver:http://localhost:9296
